import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blog Site",
  description: "Generated by Hasan",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className} >
        <div className="flex flex-col">
          <header className="bg-gray-800 text-white">
            <div className="container mx-auto flex justify-between items-center p-4">
              <div className="logo">
                <a href="/" className="text-2xl font-bold">MyLogo</a>
              </div>
              <nav className="flex space-x-4">
                <a href="/" className="hover:text-gray-400">Home</a>
                <a href="/about" className="hover:text-gray-400">About</a>
                <a href="/services" className="hover:text-gray-400">Services</a>
                <a href="/contact" className="hover:text-gray-400">Contact</a>
              </nav>
            </div>
          </header>
          <main className="flex-grow container mx-auto p-4">
            <div className="min-h-screen before:absolute before:h-[300px] before:w-full sm:before:w-[480px] before:-translate-x-1/2 before:rounded-full before:bg-gradient-radial before:from-white before:to-transparent before:blur-2xl before:content-[''] after:absolute after:-z-20 after:h-[180px] after:w-full sm:after:w-[240px] after:translate-x-1/3 after:bg-gradient-conic after:from-sky-200 after:via-blue-200 after:blur-2xl after:content-[''] before:dark:bg-gradient-to-br before:dark:from-transparent before:dark:to-blue-700 before:dark:opacity-10 after:dark:from-sky-900 after:dark:via-[#0141ff] after:dark:opacity-40 before:lg:h-[360px] z-[-1]">{children}</div>
          </main>
          <footer className="bg-gray-800 text-white mt-8">
            <div className="container mx-auto py-8">
              <div className="flex justify-between">
                <div>
                  <h2 className="font-bold text-lg mb-2">Categories</h2>
                  <ul className="space-y-2">
                    <li><a href="/privacy-policy" className="hover:text-gray-400">Healthcare</a></li>
                    <li><a href="/terms-of-service" className="hover:text-gray-400">Education</a></li>
                    <li><a href="/support" className="hover:text-gray-400">Entertainment</a></li>
                  </ul>
                </div>
                <div>
                  <h2 className="font-bold text-lg mb-2">Site Developed By</h2>
                  <p className="hover:text-gray-400">HasanZ</p>
                </div>
              </div>
            </div>
          </footer>
        </div>
      </body>
    </html>
  );
}
